<?php

namespace Blogger\BlogBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategCommentRepository extends EntityRepository
{

    public function getCommentsForCategory($categoryId)
    {
        $qb = $this->createQueryBuilder('c')
            ->select('c')
            ->where('c.category = :category_id')
            ->addOrderBy('c.create_at')
            ->setParameter('category_id', $categoryId);

        return $qb->getQuery()
            ->getResult();
    }
}
